### teste de buscar aluno por ID
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzQ3ODI5NzksInVzZXJuYW1lIjoicXdlIn0.SlYYCm8J6wlpb3i1jJcSvhSz6VjwKvzPOxza8P6-hzo

{    
    "username": "qwe",
    "password": "qwe"
}


### teste de buscar todos os alunos
GET http://localhost:40000/getAllAlunos HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzQ3ODI5NzksInVzZXJuYW1lIjoicXdlIn0.SlYYCm8J6wlpb3i1jJcSvhSz6VjwKvzPOxza8P6-hzo

{    
    
}

### teste de buscar aluno por ID
POST http://localhost:40000/getAlunoByID HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MTQxMTU5NCwiZXhwIjoxNjkxNDExODk0fQ.1Ig9H4D6QMW0TSkwJIyv7YZjBO35u5WkOpqhoSBRA1U

{    
    "alunoid": 18
}

### teste de inserção de aluno
POST http://localhost:40000/insertAlunos HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MTQzNTg3MSwiZXhwIjoxNjkxNDM2NDcxfQ.hAh0VyRfEXvYmhunlJALD-qda8pYr2zzAHobn1yua20

{    
    "alunoid": 0,
    "prontuario": "pront5",
    "nome": "Carlos das Matias",
    "endereco": " Rua das couves",
    "rendafamiliar": 10000,
    "datanascimento": "1999-12-12",
    "cursoid": 2,
    "deleted": false
}

### teste de atualização de aluno
POST http://localhost:40000/updateAlunos HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MTQzNTg3MSwiZXhwIjoxNjkxNDM2NDcxfQ.hAh0VyRfEXvYmhunlJALD-qda8pYr2zzAHobn1yua20

{    
    "alunoid": 52,
    "prontuario": "pront109",
    "nome": "xJosé das Neves",
    "endereco": "x Rua das couves",
    "rendafamiliar": 0,
    "datanascimento": "1999-12-12",
    "cursoid": 2,
    "deleted": false
}

### teste de atualização de aluno
POST http://localhost:40000/DeleteAlunos HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MTQ5MDg3NCwiZXhwIjoxNjkxNDkxNDc0fQ.1ABhMgWYm8gGKy7q90GOPQpNoY5M1LLzpCltKxFjcEo

{    
    "alunoid": 55  
}
